services:
  converter:
    build:
      context: ./converter
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${CONVERTER_PORT}:${CONVERTER_PORT}
    volumes:
      - ./shared:/app/shared

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./shared:/app/shared

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - frontend_node_modules:/app/frontend/node_modules
      - ./frontend:/app/frontend

volumes:
  frontend_node_modules:
    name: "frontend_node_modules"